name: "infra-workflow-name"

on: workflow_dispatch

permissions:
  contents: read
  id-token: write
  
jobs:
  terraform-job:
    name: job1
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 01633c86-9c38-4d47-a1c7-7c015b374c5a
        tenant-id: ccd4b901-d365-42d8-96fb-875fdb2a1dae
        subscription-id: 3bcdc0e9-b6e4-470c-86a7-c19f6b5069c8
        
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      working-directory: env/dev
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      working-directory: env/dev
      run: terraform init -input=false


    


          
    





