 name: pipeline workflow name

on: 
  push:
    branches:
    - 'main'
    - 'feature/*'
# on: workflow_dispatch ===> to run workflow manually like none


jobs:
  my_first_job:
    name: job1
    runs-on: runner-labels
    steps:
      - name: path
        run: echo hell









        
      
