name: "infra-workflow-name"

on: workflow_dispatch

jobs:
  terraform-job:
    name: job1
    runs-on: self-hosted
    
    steps:
    - name: path
      run: pwd
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: path
      run: pwd




