name: pipeline workflow name

on: 
  push:
    branches:
    - 'main'
    - 'feature/*'
# on: workflow_dispatch ===> to run workflow manually like none


jobs:
  my_first_job:
    name: job2
    runs-on: windows
    steps:
      - name: path
        run: echo hello








        
      
